/** Shown in footer when no enabled social links exist in Strapi/MongoDB. */
export const DEFAULT_SOCIAL_LINKS = [
  {
    id: "x",
    label: "X",
    url: "https://x.com/avenuebookstore",
    icon: "faXTwitter",
    enabled: true,
    order: 1,
  },
  {
    id: "facebook",
    label: "Facebook",
    url: "https://facebook.com/avenuebookstore",
    icon: "faSquareFacebook",
    enabled: true,
    order: 2,
  },
  {
    id: "instagram",
    label: "Instagram",
    url: "https://instagram.com/avenuebookstore",
    icon: "faInstagram",
    enabled: true,
    order: 3,
  },
  {
    id: "tiktok",
    label: "TikTok",
    url: "https://tiktok.com/@avenuebookstore",
    icon: "faTiktok",
    enabled: true,
    order: 4,
  },
  {
    id: "youtube",
    label: "YouTube",
    url: "https://youtube.com/@avenuebookstore",
    icon: "faYoutube",
    enabled: true,
    order: 5,
  },
  {
    id: "linkedin",
    label: "LinkedIn",
    url: "https://linkedin.com/company/avenuebookstore",
    icon: "faLinkedin",
    enabled: true,
    order: 6,
  },
];
